// <auto-generated />
using System;
using System.Net;
using AlertHub.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlertHub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AlertHubDbContext))]
    [Migration("20260911164225_Episodes")]
    partial class Episodes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlertHub.Application.Mapping.MappingVersion", b =>
                {
                    b.Property<Guid>("MappingId")
                        .HasColumnType("uuid")
                        .HasColumnName("mapping_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<int>("IdentityVersion")
                        .HasColumnType("integer")
                        .HasColumnName("identity_version");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100)
                        .HasColumnName("evaluation_order");

                    b.Property<string>("Samples")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("samples");

                    b.Property<string>("SourceYaml")
                        .HasColumnType("text")
                        .HasColumnName("source_yaml");

                    b.HasKey("MappingId", "Version");

                    b.HasIndex(new[] { "IntegrationId", "Order" }, "mapping_integration_idx");

                    b.HasIndex(new[] { "MappingId" }, "mapping_one_active_version")
                        .IsUnique()
                        .HasFilter("activated_at IS NOT NULL AND deactivated_at IS NULL");

                    b.ToTable("mapping", "cfg");
                });

            modelBuilder.Entity("AlertHub.Domain.Alerts.AlertIdentity", b =>
                {
                    b.Property<byte[]>("Fingerprint")
                        .HasColumnType("bytea")
                        .HasColumnName("fingerprint");

                    b.Property<string>("AccessScope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access_scope");

                    b.Property<string>("Components")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("components");

                    b.Property<int>("EpisodeCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("episode_count");

                    b.Property<DateTimeOffset>("FirstSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen");

                    b.Property<int>("IdentityVersion")
                        .HasColumnType("integer")
                        .HasColumnName("identity_version");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.HasKey("Fingerprint");

                    b.ToTable("identity", "alert");
                });

            modelBuilder.Entity("AlertHub.Domain.Alerts.AppliedEvent", b =>
                {
                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<string>("DeliveryKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("delivery_key");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.HasKey("IntegrationId", "DeliveryKey");

                    b.HasIndex(new[] { "EventId" }, "applied_event_event_idx");

                    b.ToTable("applied_event", "alert");
                });

            modelBuilder.Entity("AlertHub.Domain.Alerts.DeliveryDuplicate", b =>
                {
                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<string>("DeliveryKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("delivery_key");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<DateTimeOffset>("FirstSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.HasKey("IntegrationId", "DeliveryKey");

                    b.ToTable("delivery_duplicate", "alert");
                });

            modelBuilder.Entity("AlertHub.Domain.Alerts.MappingFailure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Field")
                        .HasColumnType("text")
                        .HasColumnName("field");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<int?>("MappingVersion")
                        .HasColumnType("integer")
                        .HasColumnName("mapping_version");

                    b.Property<bool>("Quarantined")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("quarantined");

                    b.Property<DateTimeOffset>("RawReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("raw_received_at");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IntegrationId", "RawReceivedAt" }, "mapping_failure_integration_idx")
                        .HasFilter("quarantined");

                    b.ToTable("mapping_failure", "alert");
                });

            modelBuilder.Entity("AlertHub.Domain.Alerts.NormalisedEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("DeliveryKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("delivery_key");

                    b.Property<string>("Dimensions")
                        .HasColumnType("jsonb")
                        .HasColumnName("dimensions");

                    b.Property<string>("Environment")
                        .HasColumnType("text")
                        .HasColumnName("environment");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("episode_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<byte[]>("Fingerprint")
                        .HasColumnType("bytea")
                        .HasColumnName("fingerprint");

                    b.Property<string>("IdentityComponents")
                        .HasColumnType("jsonb")
                        .HasColumnName("identity_components");

                    b.Property<string>("IdentityConfidence")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identity_confidence");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<string>("Labels")
                        .HasColumnType("jsonb")
                        .HasColumnName("labels");

                    b.Property<string>("LifecycleProfileHint")
                        .HasColumnType("text")
                        .HasColumnName("lifecycle_profile_hint");

                    b.Property<int>("MappingVersion")
                        .HasColumnType("integer")
                        .HasColumnName("mapping_version");

                    b.Property<DateTimeOffset?>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<DateTimeOffset>("RawReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("raw_received_at");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("ResourceId")
                        .HasColumnType("text")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceName")
                        .HasColumnType("text")
                        .HasColumnName("resource_name");

                    b.Property<string>("RuleId")
                        .HasColumnType("text")
                        .HasColumnName("rule_id");

                    b.Property<string>("RuleName")
                        .HasColumnType("text")
                        .HasColumnName("rule_name");

                    b.Property<string>("RunbookUrl")
                        .HasColumnType("text")
                        .HasColumnName("runbook_url");

                    b.Property<string>("Service")
                        .HasColumnType("text")
                        .HasColumnName("service");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<string>("SourceAlertId")
                        .HasColumnType("text")
                        .HasColumnName("source_alert_id");

                    b.Property<string>("SourceEventId")
                        .HasColumnType("text")
                        .HasColumnName("source_event_id");

                    b.Property<string>("SourceSeverity")
                        .HasColumnType("text")
                        .HasColumnName("source_severity");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.Property<string>("SourceVersion")
                        .HasColumnType("text")
                        .HasColumnName("source_version");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.HasKey("EventId");

                    b.HasIndex(new[] { "EpisodeId" }, "normalised_event_episode_idx");

                    b.HasIndex(new[] { "IntegrationId", "ReceivedAt" }, "normalised_event_integration_idx")
                        .IsDescending(false, true);

                    b.ToTable("normalised_event", "alert");
                });

            modelBuilder.Entity("AlertHub.Domain.Alerts.RawEvent", b =>
                {
                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<string>("ContentType")
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<string>("Headers")
                        .HasColumnType("jsonb")
                        .HasColumnName("headers");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<int>("SizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("size_bytes");

                    b.Property<IPAddress>("SourceIp")
                        .HasColumnType("inet")
                        .HasColumnName("source_ip");

                    b.HasKey("ReceivedAt", "EventId");

                    b.ToTable("raw_event", "alert");
                });

            modelBuilder.Entity("AlertHub.Domain.Alerts.SourceInstanceState", b =>
                {
                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<string>("SourceAlertId")
                        .HasColumnType("text")
                        .HasColumnName("source_alert_id");

                    b.Property<DateTimeOffset>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.HasKey("IntegrationId", "SourceAlertId");

                    b.ToTable("source_instance_state", "alert");
                });

            modelBuilder.Entity("AlertHub.Domain.Audit.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessScope")
                        .HasColumnType("text")
                        .HasColumnName("access_scope");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("ActorDisplay")
                        .HasColumnType("text")
                        .HasColumnName("actor_display");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_type");

                    b.Property<string>("After")
                        .HasColumnType("jsonb")
                        .HasColumnName("after");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Before")
                        .HasColumnType("jsonb")
                        .HasColumnName("before");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<IPAddress>("RequestIp")
                        .HasColumnType("inet")
                        .HasColumnName("request_ip");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_type");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ActorId", "At" }, "audit_actor_idx")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "At" }, "audit_at_idx");

                    b.HasIndex(new[] { "TargetType", "TargetId", "At" }, "audit_target_idx")
                        .IsDescending(false, false, true);

                    b.ToTable("entry", "audit");
                });

            modelBuilder.Entity("AlertHub.Domain.Episodes.Episode", b =>
                {
                    b.Property<Guid>("EpisodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("episode_id");

                    b.Property<string>("AccessScope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access_scope");

                    b.Property<DateTimeOffset?>("AckDeadlineAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ack_deadline_at");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<Guid?>("AcknowledgedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("acknowledged_by");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<DateTimeOffset?>("AutoResolveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("auto_resolve_at");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<string>("ClosureNote")
                        .HasColumnType("text")
                        .HasColumnName("closure_note");

                    b.Property<string>("ClosureReason")
                        .HasColumnType("text")
                        .HasColumnName("closure_reason");

                    b.Property<string>("ConditionState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("condition_state");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Environment")
                        .HasColumnType("text")
                        .HasColumnName("environment");

                    b.Property<byte[]>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("fingerprint");

                    b.Property<DateTimeOffset>("FirstSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen");

                    b.Property<DateTimeOffset?>("FollowUpAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("follow_up_at");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("HandlingState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("handling_state");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<bool>("IsActionable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_actionable");

                    b.Property<string>("LastAppliedVersion")
                        .HasColumnType("text")
                        .HasColumnName("last_applied_version");

                    b.Property<DateTimeOffset>("LastReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_received_at");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.Property<DateTimeOffset?>("LastVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_verified_at");

                    b.Property<int?>("LifecyclePolicyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("lifecycle_policy_version");

                    b.Property<string>("LifecycleProfile")
                        .HasColumnType("text")
                        .HasColumnName("lifecycle_profile");

                    b.Property<int>("OccurrenceCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("occurrence_count");

                    b.Property<Guid?>("OwningTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("owning_team_id");

                    b.Property<Guid?>("PreviousEpisodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_episode_id");

                    b.Property<string>("ResolutionEvidence")
                        .HasColumnType("text")
                        .HasColumnName("resolution_evidence");

                    b.Property<string>("ResourceName")
                        .HasColumnType("text")
                        .HasColumnName("resource_name");

                    b.Property<string>("RestoredFromReason")
                        .HasColumnType("text")
                        .HasColumnName("restored_from_reason");

                    b.Property<bool>("RoutingCorrectionRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("routing_correction_required");

                    b.Property<Guid?>("RoutingRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("routing_rule_id");

                    b.Property<string>("RuleName")
                        .HasColumnType("text")
                        .HasColumnName("rule_name");

                    b.Property<string>("RunbookUrl")
                        .HasColumnType("text")
                        .HasColumnName("runbook_url");

                    b.Property<string>("Service")
                        .HasColumnType("text")
                        .HasColumnName("service");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<string>("SourceAlertId")
                        .HasColumnType("text")
                        .HasColumnName("source_alert_id");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTimeOffset?>("SuppressedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suppressed_until");

                    b.Property<string>("SuppressionSource")
                        .HasColumnType("text")
                        .HasColumnName("suppression_source");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("EpisodeId");

                    b.HasIndex(new[] { "ClosedAt" }, "episode_closed_idx")
                        .HasFilter("handling_state = 'closed'");

                    b.HasIndex(new[] { "IntegrationId", "HandlingState" }, "episode_integration_idx");

                    b.HasIndex(new[] { "Fingerprint" }, "episode_one_open_per_identity")
                        .IsUnique()
                        .HasFilter("handling_state <> 'closed'");

                    b.HasIndex(new[] { "AccessScope", "HandlingState", "Severity", "LastSeen" }, "episode_queue_idx")
                        .IsDescending(false, false, false, true)
                        .HasFilter("handling_state <> 'closed'");

                    b.HasIndex(new[] { "OwningTeamId", "HandlingState", "AckDeadlineAt" }, "episode_team_idx");

                    b.ToTable("episode", "alert");
                });

            modelBuilder.Entity("AlertHub.Domain.Episodes.EpisodeEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Detail")
                        .HasColumnType("jsonb")
                        .HasColumnName("detail");

                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("episode_id");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "EpisodeId", "At" }, "episode_event_episode_idx");

                    b.ToTable("episode_event", "alert");
                });

            modelBuilder.Entity("AlertHub.Domain.Integrations.Integration", b =>
                {
                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("AccessScope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access_scope");

                    b.Property<DateTimeOffset>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Capabilities")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("capabilities");

                    b.Property<string>("Coverage")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("coverage");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("HmacConfig")
                        .HasColumnType("jsonb")
                        .HasColumnName("hmac_config");

                    b.Property<string>("HmacSecretEnc")
                        .HasColumnType("text")
                        .HasColumnName("hmac_secret_enc");

                    b.Property<string>("IngestKeyId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("ingest_key_id");

                    b.Property<string>("IngestTokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ingest_token_hash");

                    b.PrimitiveCollection<string[]>("IpAllowList")
                        .HasColumnType("text[]")
                        .HasColumnName("ip_allow_list");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_team_id");

                    b.Property<string>("ProfileDefaults")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("profile_defaults");

                    b.Property<bool>("Shadow")
                        .HasColumnType("boolean")
                        .HasColumnName("shadow");

                    b.Property<string>("SourceYaml")
                        .HasColumnType("text")
                        .HasColumnName("source_yaml");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("IntegrationId", "Version");

                    b.HasIndex(new[] { "IngestKeyId" }, "integration_ingest_key_idx")
                        .IsUnique()
                        .HasFilter("deactivated_at IS NULL");

                    b.HasIndex(new[] { "IntegrationId" }, "integration_one_current_version")
                        .IsUnique()
                        .HasFilter("deactivated_at IS NULL");

                    b.ToTable("integration", "cfg", t =>
                        {
                            t.HasCheckConstraint("integration_type_chk", "type IN ('azure_monitor','atlas','generic_webhook')");
                        });
                });

            modelBuilder.Entity("AlertHub.Domain.Ops.HubComponentHeartbeat", b =>
                {
                    b.Property<string>("Component")
                        .HasColumnType("text")
                        .HasColumnName("component");

                    b.Property<string>("Instance")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instance");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.HasKey("Component");

                    b.ToTable("hub_component_heartbeat", "ops");
                });

            modelBuilder.Entity("AlertHub.Domain.Ops.Job", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("episode_id");

                    b.Property<DateTimeOffset?>("ExpectedLastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expected_last_seen");

                    b.Property<int?>("ExpectedVersion")
                        .HasColumnType("integer")
                        .HasColumnName("expected_version");

                    b.Property<Guid?>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<int>("MaxAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("max_attempts");

                    b.Property<DateTimeOffset>("NotBefore")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_before");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<short>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)100)
                        .HasColumnName("priority");

                    b.Property<string>("ReservedBy")
                        .HasColumnType("text")
                        .HasColumnName("reserved_by");

                    b.Property<DateTimeOffset?>("ReservedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reserved_until");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("JobId");

                    b.HasIndex("Kind", "NotBefore")
                        .HasDatabaseName("job_claim_idx")
                        .HasFilter("status = 'pending'");

                    b.HasIndex(new[] { "EpisodeId", "Kind" }, "job_episode_idx")
                        .HasFilter("status IN ('pending','suspended')");

                    b.HasIndex(new[] { "EpisodeId", "Kind" }, "job_one_timer_per_episode")
                        .IsUnique()
                        .HasFilter("status IN ('pending','reserved','suspended') AND episode_id IS NOT NULL");

                    b.ToTable("job", "ops");
                });

            modelBuilder.Entity("AlertHub.Domain.Ops.OutboxMessage", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_id");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("episode_id");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("NotBefore")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_before");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int?>("PolicyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("policy_version");

                    b.Property<string>("ReservedBy")
                        .HasColumnType("text")
                        .HasColumnName("reserved_by");

                    b.Property<DateTimeOffset?>("ReservedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reserved_until");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("OutboxId");

                    b.HasIndex("NotBefore")
                        .HasDatabaseName("outbox_claim_idx")
                        .HasFilter("status = 'pending'");

                    b.HasIndex("EpisodeId", "CreatedAt")
                        .HasDatabaseName("outbox_episode_idx");

                    b.ToTable("outbox", "ops");
                });

            modelBuilder.Entity("AlertHub.Domain.Episodes.Episode", b =>
                {
                    b.HasOne("AlertHub.Domain.Alerts.AlertIdentity", null)
                        .WithMany()
                        .HasForeignKey("Fingerprint")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("episode_identity_fk");
                });

            modelBuilder.Entity("AlertHub.Domain.Episodes.EpisodeEvent", b =>
                {
                    b.HasOne("AlertHub.Domain.Episodes.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("episode_event_episode_fk");
                });
#pragma warning restore 612, 618
        }
    }
}
