// <auto-generated />
using System;
using System.Net;
using AlertHub.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlertHub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AlertHubDbContext))]
    partial class AlertHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlertHub.Domain.Alerts.RawEvent", b =>
                {
                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<string>("ContentType")
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<string>("Headers")
                        .HasColumnType("jsonb")
                        .HasColumnName("headers");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<int>("SizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("size_bytes");

                    b.Property<IPAddress>("SourceIp")
                        .HasColumnType("inet")
                        .HasColumnName("source_ip");

                    b.HasKey("ReceivedAt", "EventId");

                    b.ToTable("raw_event", "alert");
                });

            modelBuilder.Entity("AlertHub.Domain.Ops.HubComponentHeartbeat", b =>
                {
                    b.Property<string>("Component")
                        .HasColumnType("text")
                        .HasColumnName("component");

                    b.Property<string>("Instance")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instance");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.HasKey("Component");

                    b.ToTable("hub_component_heartbeat", "ops");
                });

            modelBuilder.Entity("AlertHub.Domain.Ops.Job", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("episode_id");

                    b.Property<DateTimeOffset?>("ExpectedLastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expected_last_seen");

                    b.Property<int?>("ExpectedVersion")
                        .HasColumnType("integer")
                        .HasColumnName("expected_version");

                    b.Property<Guid?>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<int>("MaxAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("max_attempts");

                    b.Property<DateTimeOffset>("NotBefore")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_before");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<short>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)100)
                        .HasColumnName("priority");

                    b.Property<string>("ReservedBy")
                        .HasColumnType("text")
                        .HasColumnName("reserved_by");

                    b.Property<DateTimeOffset?>("ReservedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reserved_until");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("JobId");

                    b.HasIndex("Kind", "NotBefore")
                        .HasDatabaseName("job_claim_idx")
                        .HasFilter("status = 'pending'");

                    b.HasIndex(new[] { "EpisodeId", "Kind" }, "job_episode_idx")
                        .HasFilter("status IN ('pending','suspended')");

                    b.HasIndex(new[] { "EpisodeId", "Kind" }, "job_one_timer_per_episode")
                        .IsUnique()
                        .HasFilter("status IN ('pending','reserved','suspended') AND episode_id IS NOT NULL");

                    b.ToTable("job", "ops");
                });

            modelBuilder.Entity("AlertHub.Domain.Ops.OutboxMessage", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_id");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("episode_id");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("NotBefore")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_before");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int?>("PolicyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("policy_version");

                    b.Property<string>("ReservedBy")
                        .HasColumnType("text")
                        .HasColumnName("reserved_by");

                    b.Property<DateTimeOffset?>("ReservedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reserved_until");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("OutboxId");

                    b.HasIndex("NotBefore")
                        .HasDatabaseName("outbox_claim_idx")
                        .HasFilter("status = 'pending'");

                    b.HasIndex("EpisodeId", "CreatedAt")
                        .HasDatabaseName("outbox_episode_idx");

                    b.ToTable("outbox", "ops");
                });
#pragma warning restore 612, 618
        }
    }
}
