// <auto-generated />
using System;
using System.Net;
using DeNoise.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeNoise.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DeNoiseDbContext))]
    [Migration("20260912120509_GroupingAndSuppression")]
    partial class GroupingAndSuppression
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeNoise.Application.Mapping.MappingVersion", b =>
                {
                    b.Property<Guid>("MappingId")
                        .HasColumnType("uuid")
                        .HasColumnName("mapping_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<int>("IdentityVersion")
                        .HasColumnType("integer")
                        .HasColumnName("identity_version");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100)
                        .HasColumnName("evaluation_order");

                    b.Property<string>("Samples")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("samples");

                    b.Property<string>("SourceYaml")
                        .HasColumnType("text")
                        .HasColumnName("source_yaml");

                    b.HasKey("MappingId", "Version");

                    b.HasIndex(new[] { "IntegrationId", "Order" }, "mapping_integration_idx");

                    b.HasIndex(new[] { "MappingId" }, "mapping_one_active_version")
                        .IsUnique()
                        .HasFilter("activated_at IS NOT NULL AND deactivated_at IS NULL");

                    b.ToTable("mapping", "cfg");
                });

            modelBuilder.Entity("DeNoise.Domain.Alerts.AlertIdentity", b =>
                {
                    b.Property<byte[]>("Fingerprint")
                        .HasColumnType("bytea")
                        .HasColumnName("fingerprint");

                    b.Property<string>("AccessScope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access_scope");

                    b.Property<string>("Components")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("components");

                    b.Property<int>("EpisodeCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("episode_count");

                    b.Property<DateTimeOffset>("FirstSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen");

                    b.Property<int>("IdentityVersion")
                        .HasColumnType("integer")
                        .HasColumnName("identity_version");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.HasKey("Fingerprint");

                    b.ToTable("identity", "alert");
                });

            modelBuilder.Entity("DeNoise.Domain.Alerts.AppliedEvent", b =>
                {
                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<string>("DeliveryKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("delivery_key");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.HasKey("IntegrationId", "DeliveryKey");

                    b.HasIndex(new[] { "EventId" }, "applied_event_event_idx");

                    b.ToTable("applied_event", "alert");
                });

            modelBuilder.Entity("DeNoise.Domain.Alerts.DeliveryDuplicate", b =>
                {
                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<string>("DeliveryKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("delivery_key");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<DateTimeOffset>("FirstSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.HasKey("IntegrationId", "DeliveryKey");

                    b.ToTable("delivery_duplicate", "alert");
                });

            modelBuilder.Entity("DeNoise.Domain.Alerts.MappingFailure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Field")
                        .HasColumnType("text")
                        .HasColumnName("field");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<int?>("MappingVersion")
                        .HasColumnType("integer")
                        .HasColumnName("mapping_version");

                    b.Property<bool>("Quarantined")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("quarantined");

                    b.Property<DateTimeOffset>("RawReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("raw_received_at");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IntegrationId", "RawReceivedAt" }, "mapping_failure_integration_idx")
                        .HasFilter("quarantined");

                    b.ToTable("mapping_failure", "alert");
                });

            modelBuilder.Entity("DeNoise.Domain.Alerts.NormalisedEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("DeliveryKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("delivery_key");

                    b.Property<string>("Dimensions")
                        .HasColumnType("jsonb")
                        .HasColumnName("dimensions");

                    b.Property<string>("Environment")
                        .HasColumnType("text")
                        .HasColumnName("environment");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("episode_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<byte[]>("Fingerprint")
                        .HasColumnType("bytea")
                        .HasColumnName("fingerprint");

                    b.Property<string>("IdentityComponents")
                        .HasColumnType("jsonb")
                        .HasColumnName("identity_components");

                    b.Property<string>("IdentityConfidence")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identity_confidence");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<string>("Labels")
                        .HasColumnType("jsonb")
                        .HasColumnName("labels");

                    b.Property<string>("LifecycleProfileHint")
                        .HasColumnType("text")
                        .HasColumnName("lifecycle_profile_hint");

                    b.Property<int>("MappingVersion")
                        .HasColumnType("integer")
                        .HasColumnName("mapping_version");

                    b.Property<DateTimeOffset?>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<DateTimeOffset>("RawReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("raw_received_at");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("ResourceId")
                        .HasColumnType("text")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceName")
                        .HasColumnType("text")
                        .HasColumnName("resource_name");

                    b.Property<string>("RuleId")
                        .HasColumnType("text")
                        .HasColumnName("rule_id");

                    b.Property<string>("RuleName")
                        .HasColumnType("text")
                        .HasColumnName("rule_name");

                    b.Property<string>("RunbookUrl")
                        .HasColumnType("text")
                        .HasColumnName("runbook_url");

                    b.Property<string>("Service")
                        .HasColumnType("text")
                        .HasColumnName("service");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<string>("SourceAlertId")
                        .HasColumnType("text")
                        .HasColumnName("source_alert_id");

                    b.Property<string>("SourceEventId")
                        .HasColumnType("text")
                        .HasColumnName("source_event_id");

                    b.Property<string>("SourceSeverity")
                        .HasColumnType("text")
                        .HasColumnName("source_severity");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.Property<string>("SourceVersion")
                        .HasColumnType("text")
                        .HasColumnName("source_version");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.HasKey("EventId");

                    b.HasIndex(new[] { "EpisodeId" }, "normalised_event_episode_idx");

                    b.HasIndex(new[] { "IntegrationId", "ReceivedAt" }, "normalised_event_integration_idx")
                        .IsDescending(false, true);

                    b.ToTable("normalised_event", "alert");
                });

            modelBuilder.Entity("DeNoise.Domain.Alerts.RawEvent", b =>
                {
                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<string>("ContentType")
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<string>("Headers")
                        .HasColumnType("jsonb")
                        .HasColumnName("headers");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<int>("SizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("size_bytes");

                    b.Property<IPAddress>("SourceIp")
                        .HasColumnType("inet")
                        .HasColumnName("source_ip");

                    b.HasKey("ReceivedAt", "EventId");

                    b.ToTable("raw_event", "alert");
                });

            modelBuilder.Entity("DeNoise.Domain.Alerts.SourceInstanceState", b =>
                {
                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<string>("SourceAlertId")
                        .HasColumnType("text")
                        .HasColumnName("source_alert_id");

                    b.Property<DateTimeOffset>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.HasKey("IntegrationId", "SourceAlertId");

                    b.ToTable("source_instance_state", "alert");
                });

            modelBuilder.Entity("DeNoise.Domain.Audit.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessScope")
                        .HasColumnType("text")
                        .HasColumnName("access_scope");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("ActorDisplay")
                        .HasColumnType("text")
                        .HasColumnName("actor_display");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_type");

                    b.Property<string>("After")
                        .HasColumnType("jsonb")
                        .HasColumnName("after");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Before")
                        .HasColumnType("jsonb")
                        .HasColumnName("before");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<IPAddress>("RequestIp")
                        .HasColumnType("inet")
                        .HasColumnName("request_ip");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_type");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ActorId", "At" }, "audit_actor_idx")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "At" }, "audit_at_idx");

                    b.HasIndex(new[] { "TargetType", "TargetId", "At" }, "audit_target_idx")
                        .IsDescending(false, false, true);

                    b.ToTable("entry", "audit");
                });

            modelBuilder.Entity("DeNoise.Domain.Episodes.AlertGroup", b =>
                {
                    b.Property<Guid>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("AccessScope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access_scope");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<string>("KeyValues")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("key_values");

                    b.Property<int>("MemberCount")
                        .HasColumnType("integer")
                        .HasColumnName("member_count");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<DateTimeOffset>("WindowEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_ends_at");

                    b.HasKey("GroupId");

                    b.HasIndex("RuleId", "KeyValues")
                        .IsUnique()
                        .HasDatabaseName("alert_group_one_open_per_key")
                        .HasFilter("closed_at IS NULL");

                    b.ToTable("alert_group", "alert");
                });

            modelBuilder.Entity("DeNoise.Domain.Episodes.Episode", b =>
                {
                    b.Property<Guid>("EpisodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("episode_id");

                    b.Property<string>("AccessScope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access_scope");

                    b.Property<DateTimeOffset?>("AckDeadlineAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ack_deadline_at");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<Guid?>("AcknowledgedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("acknowledged_by");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<DateTimeOffset?>("AutoResolveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("auto_resolve_at");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<string>("ClosureNote")
                        .HasColumnType("text")
                        .HasColumnName("closure_note");

                    b.Property<string>("ClosureReason")
                        .HasColumnType("text")
                        .HasColumnName("closure_reason");

                    b.Property<string>("ConditionState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("condition_state");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Environment")
                        .HasColumnType("text")
                        .HasColumnName("environment");

                    b.Property<byte[]>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("fingerprint");

                    b.Property<DateTimeOffset>("FirstSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen");

                    b.Property<DateTimeOffset?>("FollowUpAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("follow_up_at");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("HandlingState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("handling_state");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<bool>("IsActionable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_actionable");

                    b.Property<string>("LastAppliedVersion")
                        .HasColumnType("text")
                        .HasColumnName("last_applied_version");

                    b.Property<DateTimeOffset>("LastReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_received_at");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.Property<DateTimeOffset?>("LastVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_verified_at");

                    b.Property<Guid?>("LifecyclePolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("lifecycle_policy_id");

                    b.Property<int?>("LifecyclePolicyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("lifecycle_policy_version");

                    b.Property<string>("LifecycleProfile")
                        .HasColumnType("text")
                        .HasColumnName("lifecycle_profile");

                    b.Property<int>("OccurrenceCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("occurrence_count");

                    b.Property<Guid?>("OwningTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("owning_team_id");

                    b.Property<Guid?>("PreviousEpisodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_episode_id");

                    b.Property<string>("ResolutionEvidence")
                        .HasColumnType("text")
                        .HasColumnName("resolution_evidence");

                    b.Property<string>("ResourceName")
                        .HasColumnType("text")
                        .HasColumnName("resource_name");

                    b.Property<string>("RestoredFromReason")
                        .HasColumnType("text")
                        .HasColumnName("restored_from_reason");

                    b.Property<bool>("RoutingCorrectionRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("routing_correction_required");

                    b.Property<Guid?>("RoutingRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("routing_rule_id");

                    b.Property<string>("RuleName")
                        .HasColumnType("text")
                        .HasColumnName("rule_name");

                    b.Property<string>("RunbookUrl")
                        .HasColumnType("text")
                        .HasColumnName("runbook_url");

                    b.Property<string>("Service")
                        .HasColumnType("text")
                        .HasColumnName("service");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<string>("SourceAlertId")
                        .HasColumnType("text")
                        .HasColumnName("source_alert_id");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.Property<DateTimeOffset?>("StaleSince")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stale_since");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTimeOffset?>("SuppressedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suppressed_until");

                    b.Property<string>("SuppressionSource")
                        .HasColumnType("text")
                        .HasColumnName("suppression_source");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("EpisodeId");

                    b.HasIndex(new[] { "ClosedAt" }, "episode_closed_idx")
                        .HasFilter("handling_state = 'closed'");

                    b.HasIndex(new[] { "IntegrationId", "HandlingState" }, "episode_integration_idx");

                    b.HasIndex(new[] { "Fingerprint" }, "episode_one_open_per_identity")
                        .IsUnique()
                        .HasFilter("handling_state <> 'closed'");

                    b.HasIndex(new[] { "AccessScope", "HandlingState", "Severity", "LastSeen" }, "episode_queue_idx")
                        .IsDescending(false, false, false, true)
                        .HasFilter("handling_state <> 'closed'");

                    b.HasIndex(new[] { "OwningTeamId", "HandlingState", "AckDeadlineAt" }, "episode_team_idx");

                    b.ToTable("episode", "alert");
                });

            modelBuilder.Entity("DeNoise.Domain.Episodes.EpisodeEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Detail")
                        .HasColumnType("jsonb")
                        .HasColumnName("detail");

                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("episode_id");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "EpisodeId", "At" }, "episode_event_episode_idx");

                    b.ToTable("episode_event", "alert");
                });

            modelBuilder.Entity("DeNoise.Domain.Heartbeats.Heartbeat", b =>
                {
                    b.Property<Guid>("HeartbeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("heartbeat_id");

                    b.Property<string>("AccessScope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access_scope");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<bool>("AutoPauseDuringMaintenance")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_pause_during_maintenance");

                    b.Property<Guid?>("BindsToIntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("binds_to_integration_id");

                    b.Property<int>("ConsecutiveSuccesses")
                        .HasColumnType("integer")
                        .HasColumnName("consecutive_successes");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Cron")
                        .HasColumnType("text")
                        .HasColumnName("cron");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("ExpectedNext")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expected_next");

                    b.Property<TimeSpan>("Grace")
                        .HasColumnType("interval")
                        .HasColumnName("grace");

                    b.Property<TimeSpan?>("Interval")
                        .HasColumnType("interval")
                        .HasColumnName("interval");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_id");

                    b.Property<DateTimeOffset?>("LastPingAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_ping_at");

                    b.Property<IPAddress>("LastPingIp")
                        .HasColumnType("inet")
                        .HasColumnName("last_ping_ip");

                    b.Property<TimeSpan?>("LastRunDuration")
                        .HasColumnType("interval")
                        .HasColumnName("last_run_duration");

                    b.Property<Guid?>("MissEpisodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("miss_episode_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OwningTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("owning_team_id");

                    b.Property<string>("PauseReason")
                        .HasColumnType("text")
                        .HasColumnName("pause_reason");

                    b.Property<DateTimeOffset?>("PausedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paused_at");

                    b.Property<Guid?>("PausedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("paused_by");

                    b.Property<bool>("PausedByMaintenance")
                        .HasColumnType("boolean")
                        .HasColumnName("paused_by_maintenance");

                    b.Property<int>("RecoverySuccessesRequired")
                        .HasColumnType("integer")
                        .HasColumnName("recovery_successes_required");

                    b.Property<Guid?>("RoutingPolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("routing_policy_id");

                    b.Property<DateTimeOffset?>("RunStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_started_at");

                    b.Property<string>("ScheduleKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("schedule_kind");

                    b.Property<string>("ScheduleTz")
                        .HasColumnType("text")
                        .HasColumnName("schedule_tz");

                    b.Property<string>("SeverityOnMiss")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity_on_miss");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset>("TokenRotatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("token_rotated_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("HeartbeatId");

                    b.HasIndex(new[] { "BindsToIntegrationId" }, "hb_binding_idx");

                    b.HasIndex(new[] { "ExpectedNext" }, "hb_due_idx")
                        .HasFilter("state IN ('healthy','late')");

                    b.HasIndex(new[] { "KeyId" }, "hb_key_idx")
                        .IsUnique();

                    b.HasIndex(new[] { "OwningTeamId", "State" }, "hb_team_idx");

                    b.ToTable("heartbeat", "hb");
                });

            modelBuilder.Entity("DeNoise.Domain.Heartbeats.HeartbeatRun", b =>
                {
                    b.Property<Guid>("HeartbeatId")
                        .HasColumnType("uuid")
                        .HasColumnName("heartbeat_id");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("integer")
                        .HasColumnName("exit_code");

                    b.Property<DateTimeOffset>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<IPAddress>("SourceIp")
                        .HasColumnType("inet")
                        .HasColumnName("source_ip");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("HeartbeatId", "Seq");

                    b.ToTable("run", "hb");
                });

            modelBuilder.Entity("DeNoise.Domain.Integrations.Integration", b =>
                {
                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("AccessScope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access_scope");

                    b.Property<DateTimeOffset>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Capabilities")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("capabilities");

                    b.Property<string>("Coverage")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("coverage");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("HmacConfig")
                        .HasColumnType("jsonb")
                        .HasColumnName("hmac_config");

                    b.Property<string>("HmacSecretEnc")
                        .HasColumnType("text")
                        .HasColumnName("hmac_secret_enc");

                    b.Property<string>("IngestKeyId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("ingest_key_id");

                    b.Property<string>("IngestTokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ingest_token_hash");

                    b.PrimitiveCollection<string[]>("IpAllowList")
                        .HasColumnType("text[]")
                        .HasColumnName("ip_allow_list");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_team_id");

                    b.Property<string>("ProfileDefaults")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("profile_defaults");

                    b.Property<bool>("Shadow")
                        .HasColumnType("boolean")
                        .HasColumnName("shadow");

                    b.Property<string>("SourceYaml")
                        .HasColumnType("text")
                        .HasColumnName("source_yaml");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("IntegrationId", "Version");

                    b.HasIndex(new[] { "IngestKeyId" }, "integration_ingest_key_idx")
                        .IsUnique()
                        .HasFilter("deactivated_at IS NULL");

                    b.HasIndex(new[] { "IntegrationId" }, "integration_one_current_version")
                        .IsUnique()
                        .HasFilter("deactivated_at IS NULL");

                    b.ToTable("integration", "cfg", t =>
                        {
                            t.HasCheckConstraint("integration_type_chk", "type IN ('azure_monitor','atlas','generic_webhook')");
                        });
                });

            modelBuilder.Entity("DeNoise.Domain.Notifications.DeliveryAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempted_at");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<int?>("HttpStatus")
                        .HasColumnType("integer")
                        .HasColumnName("http_status");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<Guid>("OutboxId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<string>("ResponseExcerpt")
                        .HasColumnType("text")
                        .HasColumnName("response_excerpt");

                    b.Property<bool>("UsedFallback")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("used_fallback");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AttemptedAt" }, "delivery_attempt_at_idx");

                    b.HasIndex(new[] { "OutboxId" }, "delivery_attempt_outbox_idx");

                    b.ToTable("delivery_attempt", "ops");
                });

            modelBuilder.Entity("DeNoise.Domain.Notifications.Destination", b =>
                {
                    b.Property<Guid>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("destination_id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<Guid?>("BodyTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("body_template_id");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel_type");

                    b.Property<int>("ConsecutiveFailures")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("consecutive_failures");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<string[]>("EmailTo")
                        .HasColumnType("text[]")
                        .HasColumnName("email_to");

                    b.PrimitiveCollection<string[]>("EventTypes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("event_types");

                    b.Property<Guid>("FallbackDestinationId")
                        .HasColumnType("uuid")
                        .HasColumnName("fallback_destination_id");

                    b.Property<string>("HeadersEnc")
                        .HasColumnType("text")
                        .HasColumnName("headers_enc");

                    b.Property<DateTimeOffset?>("LastFailureAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_failure_at");

                    b.Property<DateTimeOffset?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_success_at");

                    b.Property<string>("Method")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("POST")
                        .HasColumnName("method");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("RetryPolicy")
                        .HasColumnType("jsonb")
                        .HasColumnName("retry_policy");

                    b.Property<string>("SigningSecretEnc")
                        .HasColumnType("text")
                        .HasColumnName("signing_secret_enc");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<TimeSpan>("Timeout")
                        .HasColumnType("interval")
                        .HasColumnName("timeout");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UrlEnc")
                        .HasColumnType("text")
                        .HasColumnName("url_enc");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("DestinationId");

                    b.HasIndex(new[] { "TeamId" }, "destination_team_idx");

                    b.ToTable("destination", "cfg", t =>
                        {
                            t.HasCheckConstraint("destination_channel_chk", "channel_type IN ('webhook','smtp_email')");

                            t.HasCheckConstraint("destination_fallback_not_self_chk", "fallback_destination_id <> destination_id");
                        });
                });

            modelBuilder.Entity("DeNoise.Domain.Notifications.WebhookTemplate", b =>
                {
                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<bool>("Builtin")
                        .HasColumnType("boolean")
                        .HasColumnName("builtin");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("format");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SampleOutput")
                        .HasColumnType("text")
                        .HasColumnName("sample_output");

                    b.HasKey("TemplateId", "Version");

                    b.HasIndex(new[] { "TemplateId" }, "webhook_template_one_active")
                        .IsUnique()
                        .HasFilter("activated_at IS NOT NULL AND deactivated_at IS NULL");

                    b.ToTable("webhook_template", "cfg");
                });

            modelBuilder.Entity("DeNoise.Domain.Ops.CoverageState", b =>
                {
                    b.Property<Guid>("IntegrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<int>("ConsecutiveSuccesses")
                        .HasColumnType("integer")
                        .HasColumnName("consecutive_successes");

                    b.Property<Guid?>("CoverageEpisodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("coverage_episode_id");

                    b.Property<string>("Detail")
                        .HasColumnType("jsonb")
                        .HasColumnName("detail");

                    b.Property<DateTimeOffset?>("LastProcessedAlertAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_processed_alert_at");

                    b.Property<DateTimeOffset?>("LastSignalAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_signal_at");

                    b.Property<DateTimeOffset>("Since")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("since");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("IntegrationId");

                    b.ToTable("coverage_state", "ops");
                });

            modelBuilder.Entity("DeNoise.Domain.Ops.HubComponentHeartbeat", b =>
                {
                    b.Property<string>("Component")
                        .HasColumnType("text")
                        .HasColumnName("component");

                    b.Property<string>("Instance")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instance");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.HasKey("Component");

                    b.ToTable("hub_component_heartbeat", "ops");
                });

            modelBuilder.Entity("DeNoise.Domain.Ops.Job", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("episode_id");

                    b.Property<DateTimeOffset?>("ExpectedLastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expected_last_seen");

                    b.Property<int?>("ExpectedVersion")
                        .HasColumnType("integer")
                        .HasColumnName("expected_version");

                    b.Property<Guid?>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<int>("MaxAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("max_attempts");

                    b.Property<DateTimeOffset>("NotBefore")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_before");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<short>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)100)
                        .HasColumnName("priority");

                    b.Property<string>("ReservedBy")
                        .HasColumnType("text")
                        .HasColumnName("reserved_by");

                    b.Property<DateTimeOffset?>("ReservedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reserved_until");

                    b.Property<string>("Result")
                        .HasColumnType("jsonb")
                        .HasColumnName("result");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("JobId");

                    b.HasIndex("Kind", "NotBefore")
                        .HasDatabaseName("job_claim_idx")
                        .HasFilter("status = 'pending'");

                    b.HasIndex(new[] { "EpisodeId", "Kind" }, "job_episode_idx")
                        .HasFilter("status IN ('pending','suspended')");

                    b.HasIndex(new[] { "EpisodeId", "Kind" }, "job_one_timer_per_episode")
                        .IsUnique()
                        .HasFilter("status IN ('pending','reserved','suspended') AND episode_id IS NOT NULL");

                    b.ToTable("job", "ops");
                });

            modelBuilder.Entity("DeNoise.Domain.Ops.OutboxMessage", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_id");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("episode_id");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("NotBefore")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_before");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int?>("PolicyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("policy_version");

                    b.Property<string>("ReservedBy")
                        .HasColumnType("text")
                        .HasColumnName("reserved_by");

                    b.Property<DateTimeOffset?>("ReservedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reserved_until");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("OutboxId");

                    b.HasIndex("NotBefore")
                        .HasDatabaseName("outbox_claim_idx")
                        .HasFilter("status = 'pending'");

                    b.HasIndex("EpisodeId", "CreatedAt")
                        .HasDatabaseName("outbox_episode_idx");

                    b.ToTable("outbox", "ops");
                });

            modelBuilder.Entity("DeNoise.Domain.Policies.PolicyVersion", b =>
                {
                    b.Property<string>("Kind")
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SourceYaml")
                        .HasColumnType("text")
                        .HasColumnName("source_yaml");

                    b.HasKey("Kind", "PolicyId", "Version");

                    b.HasIndex(new[] { "Kind", "PolicyId" }, "policy_one_active_version")
                        .IsUnique()
                        .HasFilter("activated_at IS NOT NULL AND deactivated_at IS NULL");

                    b.ToTable("policy", "cfg", t =>
                        {
                            t.HasCheckConstraint("policy_kind_chk", "kind IN ('routing','escalation','lifecycle','grouping')");
                        });
                });

            modelBuilder.Entity("DeNoise.Domain.Policies.Suppression", b =>
                {
                    b.Property<Guid>("SuppressionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("suppression_id");

                    b.Property<bool>("AutoPauseHeartbeats")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_pause_heartbeats");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("CancelledBy")
                        .HasColumnType("text")
                        .HasColumnName("cancelled_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("scope");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<DateTimeOffset?>("SummarySentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("summary_sent_at");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tz");

                    b.HasKey("SuppressionId");

                    b.HasIndex("StartsAt", "EndsAt")
                        .HasDatabaseName("suppression_window_idx");

                    b.ToTable("suppression", "cfg");
                });

            modelBuilder.Entity("DeNoise.Domain.Teams.AccessScope", b =>
                {
                    b.Property<string>("Scope")
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.PrimitiveCollection<string[]>("EntraGroupIds")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("entra_group_ids");

                    b.Property<string>("Product")
                        .HasColumnType("text")
                        .HasColumnName("product");

                    b.HasKey("Scope");

                    b.ToTable("scope", "cfg");
                });

            modelBuilder.Entity("DeNoise.Domain.Teams.Team", b =>
                {
                    b.Property<Guid>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.PrimitiveCollection<string[]>("AccessScopes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("access_scopes");

                    b.Property<string>("CoverageHours")
                        .HasColumnType("jsonb")
                        .HasColumnName("coverage_hours");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DefaultEscalationPolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_escalation_policy_id");

                    b.PrimitiveCollection<string[]>("EntraGroupIds")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("entra_group_ids");

                    b.Property<Guid?>("FallbackTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("fallback_team_id");

                    b.Property<bool>("IsTriage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_triage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("TeamId");

                    b.HasIndex(new[] { "Name" }, "team_name_uq")
                        .IsUnique();

                    b.HasIndex(new[] { "IsTriage" }, "team_one_triage")
                        .IsUnique()
                        .HasFilter("is_triage");

                    b.ToTable("team", "cfg");
                });

            modelBuilder.Entity("DeNoise.Domain.Users.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request_fingerprint");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("text")
                        .HasColumnName("response_body");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.HasKey("UserId", "Key");

                    b.HasIndex(new[] { "ExpiresAt" }, "idempotency_expires_idx");

                    b.ToTable("idempotency_key", "cfg");
                });

            modelBuilder.Entity("DeNoise.Domain.Users.LoginAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<IPAddress>("Ip")
                        .HasColumnType("inet")
                        .HasColumnName("ip");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Ip", "At" }, "login_attempt_ip_idx");

                    b.HasIndex(new[] { "Username", "At" }, "login_attempt_user_idx");

                    b.ToTable("login_attempt", "cfg");
                });

            modelBuilder.Entity("DeNoise.Domain.Users.PersonalAccessToken", b =>
                {
                    b.Property<Guid>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("token_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("key_id");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.PrimitiveCollection<string[]>("Scopes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("scopes");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("TokenId");

                    b.HasIndex(new[] { "KeyId" }, "pat_key_uq")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "pat_user_idx");

                    b.ToTable("personal_access_token", "cfg");
                });

            modelBuilder.Entity("DeNoise.Domain.Users.SavedFilter", b =>
                {
                    b.Property<Guid>("FilterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("filter_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("query");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("FilterId");

                    b.HasIndex(new[] { "UserId", "Name" }, "saved_filter_user_name_uq")
                        .IsUnique();

                    b.ToTable("saved_filter", "cfg");
                });

            modelBuilder.Entity("DeNoise.Domain.Users.Session", b =>
                {
                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset>("AbsoluteExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("absolute_expires_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<IPAddress>("Ip")
                        .HasColumnType("inet")
                        .HasColumnName("ip");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("SessionId");

                    b.HasIndex(new[] { "ExpiresAt" }, "session_expires_idx");

                    b.HasIndex(new[] { "UserId", "ExpiresAt" }, "session_user_idx");

                    b.ToTable("session", "cfg");
                });

            modelBuilder.Entity("DeNoise.Domain.Users.TeamMember", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("member")
                        .HasColumnName("role");

                    b.HasKey("TeamId", "UserId");

                    b.HasIndex(new[] { "UserId" }, "team_member_user_idx");

                    b.ToTable("team_member", "cfg");
                });

            modelBuilder.Entity("DeNoise.Domain.Users.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("local")
                        .HasColumnName("auth_provider");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("Disabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("disabled");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<int>("FailedAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_attempts");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("must_change_password");

                    b.Property<DateTimeOffset?>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_changed_at");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.PrimitiveCollection<string[]>("RoleNames")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("roles");

                    b.PrimitiveCollection<string[]>("Scopes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("scopes");

                    b.Property<string>("TotpSecretEnc")
                        .HasColumnType("text")
                        .HasColumnName("totp_secret_enc");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "Email" }, "user_email_uq")
                        .IsUnique()
                        .HasFilter("email IS NOT NULL");

                    b.HasIndex(new[] { "Username" }, "user_username_uq")
                        .IsUnique();

                    b.ToTable("user", "cfg", t =>
                        {
                            t.HasCheckConstraint("user_provider_chk", "auth_provider IN ('local','oidc')");
                        });
                });

            modelBuilder.Entity("DeNoise.Domain.Episodes.Episode", b =>
                {
                    b.HasOne("DeNoise.Domain.Alerts.AlertIdentity", null)
                        .WithMany()
                        .HasForeignKey("Fingerprint")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("episode_identity_fk");
                });

            modelBuilder.Entity("DeNoise.Domain.Episodes.EpisodeEvent", b =>
                {
                    b.HasOne("DeNoise.Domain.Episodes.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("episode_event_episode_fk");
                });

            modelBuilder.Entity("DeNoise.Domain.Notifications.Destination", b =>
                {
                    b.HasOne("DeNoise.Domain.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("destination_team_fk");
                });

            modelBuilder.Entity("DeNoise.Domain.Users.PersonalAccessToken", b =>
                {
                    b.HasOne("DeNoise.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("pat_user_fk");
                });

            modelBuilder.Entity("DeNoise.Domain.Users.SavedFilter", b =>
                {
                    b.HasOne("DeNoise.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("saved_filter_user_fk");
                });

            modelBuilder.Entity("DeNoise.Domain.Users.Session", b =>
                {
                    b.HasOne("DeNoise.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("session_user_fk");
                });

            modelBuilder.Entity("DeNoise.Domain.Users.TeamMember", b =>
                {
                    b.HasOne("DeNoise.Domain.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("team_member_team_fk");

                    b.HasOne("DeNoise.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("team_member_user_fk");
                });
#pragma warning restore 612, 618
        }
    }
}
